CREATE 
  (kpi1:KPI {name: 'SupportTicketKPI', owner: 'Support Manager'}),
  (kpi2:KPI {name: 'ProfitMarginKPI', owner: 'CFO'}),
  (kpi3:KPI {name: 'SalesKPIStatus', owner: 'Sales Manager'}),
  (kpi4:KPI {name: 'InventoryKPIStatus', owner: 'Inventory Manager'}),
  (kpi5:KPI {name: 'NewCustomerKPIStatus', owner: 'Marketing Manager'}),
  (kpi6:KPI {name: 'ProfitMarginKPI', owner: 'Warranty Manager'}),
  
  (e1:Element {name: 'dbo.FactSupportTickets.ProductKey', elementName: 'ProductKey', dataSource: 'AdventureWorksDW'}),
  (e2:Element {name: 'dbo.FactProductInventory.ProductKey', elementName: 'ProductKey', dataSource: 'AdventureWorksDW'}),
  (e3:Element {name: 'dbo.FactProductInventory.MovementDate', elementName: 'MovementDate', dataSource: 'AdventureWorksDW'}),
  (e4:Element {name: 'dbo.FactInternetSales.SalesAmount', elementName: 'SalesAmount', dataSource: 'AdventureWorksDW'}),
  (e5:Element {name: 'dbo.FactInternetSales.TotalCost', elementName: 'TotalCost', dataSource: 'AdventureWorksDW'}),
  (e6:Element {name: 'dbo.FactInternetSales.OrderDate', elementName: 'OrderDate', dataSource: 'AdventureWorksDW'}),
  (e7:Element {name: 'dbo.FactProductInventory.UnitsBalance', elementName: 'UnitsBalance', dataSource: 'AdventureWorksDW'}),
  (e8:Element {name: 'dbo.FactProductInventory.ReorderPoint', elementName: 'ReorderPoint', dataSource: 'AdventureWorksDW'}),
  (e9:Element {name: 'dbo.FactInternetSales.CustomerKey', elementName: 'CustomerKey', dataSource: 'AdventureWorksDW'}),
  (e10:Element {name: 'dbo.WarrantyFacts.ItemSalesAmount', elementName: 'ItemSalesAmount', dataSource: 'Warranty Database'}),
  (e11:Element {name: 'dbo.WarrantyFacts.WarrantyCharges', elementName: 'WarrantyCharges', dataSource: 'Warranty Database'}),
  (e12:Element {name: 'dbo.FactInternetSales.OrderQuantity', elementName: 'OrderQuantity', dataSource: 'AdventureWorksDW'}),
  (kpi1)-[:HAS_ELEMENT {relationship: 'References', filter: false, calculation: true}]->(e1),
  (kpi1)-[:HAS_ELEMENT {relationship: 'References', filter: true, calculation: true}]->(e2),
  (kpi1)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: true, calculation: false}]->(e3),
  (kpi2)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: false, calculation: true}]->(e4),
  (kpi2)-[:HAS_ELEMENT {relationship: 'Inverse Reciprocal', filter: false, calculation: true}]->(e5),
  (kpi2)-[:HAS_ELEMENT {relationship: 'References', filter: true, calculation: false}]->(e6),
  (kpi3)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: false, calculation: true}]->(e4),
  (kpi3)-[:HAS_ELEMENT {relationship: 'References', filter: true, calculation: false}]->(e6),
  (kpi4)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: false, calculation: true}]->(e7),
  (kpi4)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: false, calculation: true}]->(e8),
  (kpi4)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: true, calculation: false}]->(e3),
  (kpi5)-[:HAS_ELEMENT {relationship: 'References', filter: false, calculation: true}]->(e9),
  (kpi5)-[:HAS_ELEMENT {relationship: 'References', filter: true, calculation: false}]->(e6),
  (kpi6)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: false, calculation: true}]->(e10),
  (kpi6)-[:HAS_ELEMENT {relationship: 'Inverse Reciprocal', filter: false, calculation: true}]->(e11),
  (e4)-[:SIMILAR_TO {description: 'SalesAmount is derived from OrderQuantity * UnitPrice.', probability: 1.0}]->(e12),
  (e7)-[:SIMILAR_TO {description: 'Both represent quantities of items in different contexts.', probability: 0.8}]->(e12),
  (e8)-[:SIMILAR_TO {description: 'Both represent quantities of items in different contexts.', probability: 0.8}]->(e12),
  (e4)-[:SIMILAR_TO {description: 'Semantically they might refer to the same concept but come from different databases and tables.', probability: 0.5}]->(e10);
