CREATE 
  (kpi1:KPI {name: 'SupportTicketKPI', owner: 'Support Manager'}),
  (kpi2:KPI {name: 'ProfitMarginKPI_CFO', owner: 'CFO'}),
  (kpi3:KPI {name: 'SalesKPIStatus', owner: 'Sales Manager'}),
  (kpi4:KPI {name: 'InventoryKPIStatus', owner: 'Inventory Manager'}),
  (kpi5:KPI {name: 'NewCustomerKPIStatus', owner: 'Marketing Manager'}),
  (kpi6:KPI {name: 'ProfitMarginKPI_Warranty', owner: 'Warranty Manager'}),
  (kpi7:KPI {name: 'hr_retention_kpi', owner: 'HR'}),
  (e1:Element {elementName: 'ProductKey', fullName: 'dbo.FactSupportTickets.ProductKey', dataSource: 'AdventureWorksDW'}),
  (e2:Element {elementName: 'SnapshotDate', fullName: '@SnapshotDate', dataSource: 'Variable'}),
  (e3:Element {elementName: 'SalesAmount', fullName: 'dbo.FactInternetSales.SalesAmount', dataSource: 'AdventureWorksDW'}),
  (e4:Element {elementName: 'TotalCost', fullName: 'dbo.FactInternetSales.TotalCost', dataSource: 'AdventureWorksDW'}),
  (e5:Element {elementName: 'OrderDate', fullName: 'dbo.FactInternetSales.OrderDate', dataSource: 'AdventureWorksDW'}),
  (e6:Element {elementName: 'SalesGoal', fullName: '@SalesGoal', dataSource: 'Variable'}),
  (e7:Element {elementName: 'UnitsBalance', fullName: 'dbo.FactProductInventory.UnitsBalance', dataSource: 'AdventureWorksDW'}),
  (e8:Element {elementName: 'ReorderPoint', fullName: 'dbo.FactProductInventory.ReorderPoint', dataSource: 'AdventureWorksDW'}),
  (e9:Element {elementName: 'CustomerTarget', fullName: '@CustomerTarget', dataSource: 'Variable'}),
  (e10:Element {elementName: 'CustomerKey', fullName: 'dbo.FactInternetSales.CustomerKey', dataSource: 'AdventureWorksDW'}),
  (e11:Element {elementName: 'FirstPurchaseDate', fullName: 'CustomerPurchases.FirstPurchaseDate', dataSource: 'Derived'}),
  (e12:Element {elementName: 'ItemSalesAmount', fullName: 'dbo.WarrantyFacts.ItemSalesAmount', dataSource: 'Custom'}),
  (e13:Element {elementName: 'WarrantyCharges', fullName: 'dbo.WarrantyFacts.WarrantyCharges', dataSource: 'Custom'}),
  (e14:Element {elementName: 'department', fullName: 'department', dataSource: 'HR System'}),
  (e15:Element {elementName: 'month_count', fullName: 'month_count', dataSource: 'HR System'}),
  (e16:Element {elementName: 'last_month_count', fullName: 'last_month_count', dataSource: 'HR System'}),
  
  (kpi1)-[:HAS_ELEMENT {relationship: 'N/A', filter: 'Yes', calculation: 'Yes'}]->(e1),
  (kpi1)-[:HAS_ELEMENT {relationship: 'N/A', filter: 'Yes', calculation: 'Yes'}]->(e2),
  (kpi2)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: 'No', calculation: 'Yes'}]->(e3),
  (kpi2)-[:HAS_ELEMENT {relationship: 'Inverse Reciprocal', filter: 'No', calculation: 'Yes'}]->(e4),
  (kpi3)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: 'Yes', calculation: 'Yes'}]->(e3),
  (kpi3)-[:HAS_ELEMENT {relationship: 'N/A', filter: 'Yes', calculation: 'No'}]->(e5),
  (kpi3)-[:HAS_ELEMENT {relationship: 'N/A', filter: 'Yes', calculation: 'No'}]->(e6),
  (kpi4)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: 'No', calculation: 'Yes'}]->(e7),
  (kpi4)-[:HAS_ELEMENT {relationship: 'Inverse Reciprocal', filter: 'No', calculation: 'Yes'}]->(e8),
  (kpi5)-[:HAS_ELEMENT {relationship: 'N/A', filter: 'Yes', calculation: 'No'}]->(e9),
  (kpi5)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: 'Yes', calculation: 'Yes'}]->(e10),
  (kpi5)-[:HAS_ELEMENT {relationship: 'N/A', filter: 'Yes', calculation: 'No'}]->(e11),
  (kpi6)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: 'No', calculation: 'Yes'}]->(e12),
  (kpi6)-[:HAS_ELEMENT {relationship: 'Inverse Reciprocal', filter: 'No', calculation: 'Yes'}]->(e13),
  (kpi7)-[:HAS_ELEMENT {relationship: 'Inverse Reciprocal', filter: 'No', calculation: 'Yes'}]->(e14),
  (kpi7)-[:HAS_ELEMENT {relationship: 'Inverse Reciprocal', filter: 'No', calculation: 'Yes'}]->(e15),
  (kpi7)-[:HAS_ELEMENT {relationship: 'Directly Proportional', filter: 'No', calculation: 'Yes'}]->(e16),
  
  (e3)-[:SIMILAR_TO {description: 'SalesAmount and OrderDate are related to sales data', probability: 0.7}]->(e5),
  (e3)-[:SIMILAR_TO {description: 'SalesAmount and SalesGoal are related to sales data', probability: 0.8}]->(e6),
  (e3)-[:SIMILAR_TO {description: 'SalesAmount and UnitsBalance are related to item quantities', probability: 0.9}]->(e7),
  (e3)-[:SIMILAR_TO {description: 'SalesAmount and ReorderPoint are related to item quantities', probability: 0.9}]->(e8),
  (e3)-[:SIMILAR_TO {description: 'SalesAmount and CustomerTarget are related to customers', probability: 0.7}]->(e9),
  (e3)-[:SIMILAR_TO {description: 'SalesAmount and CustomerKey are related to customers', probability: 0.9}]->(e10),
  (e3)-[:SIMILAR_TO {description: 'SalesAmount and FirstPurchaseDate are related to customers', probability: 0.8}]->(e11),
  (e3)-[:SIMILAR_TO {description: 'SalesAmount and ItemSalesAmount are related to sales data', probability: 0.8}]->(e12),
  (e3)-[:SIMILAR_TO {description: 'SalesAmount and WarrantyCharges are related to sales data', probability: 0.7}]->(e13)
;
